language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Set package name for downstream devtools.
  - export PACKAGENAME="openmmtools"
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=33
    - CONDA_PY=34
  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
  - secure: "RMyNnsH1n7y8S+jJeYTdu3Lu4GF0NMERBCbf7yMf7ptTVvJx7+bOz/l9+/Ap+tEdXomow6i8Lrk/uG9+DOYHl3WBhYqIywtv10anP83opkUlOAcrIBDpf4B72dBgNJ5Oc5evEsf9hkMcdYrqI/GkcKFUYq2knEJtDGP6TsDHJic="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
